const questionsData = [
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 },
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the process of photosynthesis", subject: "Biology", topic: "Genetics", difficulty: "Medium", marks: 10 },
    { question: "Explain the process of cynide", subject: "Chemistry", topic: "Reactions", difficulty: "Hard", marks: 15 }
    // Add more questions as needed
];

module.exports = questionsData;